{% set name = "anuga" %}
{% set version = "3.3.0" %}
{% set sha = "550138efaabac6a3ec5c52f0d937e3039ddc7d3ded778fe3a5f4a9cfd1b2c1fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anuga-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  script: {{ PYTHON }} -m pip install . --no-build-isolation -vv
  number: 0
  skip: True  # [py<3.10]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - cython
    - meson-python
    - ninja
    - numpy >=2.0.0
    - pybind11
    - libpython  # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - dill >=0.3.7
    - matplotlib-base >=3.7
    - meshpy >=2022.1
    - netcdf4 >=1.6
    - scipy >=1.11

  run_constrained:
    - mpi4py
    - pymetis >=2023.1
    - pyproj >=3.6
    - affine >=2.4
    - rasterio
    - fiona
    - shapely
    - xarray
    - pandas
    - openpyxl

test:
  imports:
    - anuga
  commands:
    - pytest --pyargs anuga --run-fast -x -q
  requires:
    - pytest

about:
  home: https://github.com/anuga-community/anuga_core
  summary: A set of python modules for tsunami and flood modelling
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - stoiver
