{% set name = "anuga" %}
{% set version = "3.2.0" %}
{% set sha = "a6c7fd2d4e22d6f8befd23f6a502eb6e96da99ff49816fac3e09c3f2aeb41a17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anuga-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<3.6]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - m2w64-gcc                  # [win]
    - libpython                  # [win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - python
    - libpython  # [win]
    - pip
    - cython
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - dill
    - future
    - gdal >=3.0.4
    - matplotlib-base
    - meshpy
    - netcdf4
    - Pmw
    - pymetis
    - pytest
    - pytz
    - scipy
    - utm

test:
  imports:
    - anuga
  commands:
    - pytest --pyargs anuga
  requires:
    - pytest

about:
  home: https://github.com/anuga-community/anuga_core
  summary: A set of python modules for tsunami and flood modelling
  license: AGPL-1.0-or-later
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - stoiver
