{% set name = "anuga" %}
{% set version = "3.2.0" %}
{% set sha = "a6c7fd2d4e22d6f8befd23f6a502eb6e96da99ff49816fac3e09c3f2aeb41a17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anuga-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True  # [py<3.9]


requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - gcc_win-64                 # [win]
    - gxx_win-64                 # [win]
    - libpython                  # [win]
    - {{ stdlib("c") }}
    - toml
    - cython
    - meson-python
    - ninja
    - numpy >=2.0.0

  host:
    - python 
    - libpython  # [win]
    - pip
    - toml
    - cython
    - meson-python
    - ninja  
    - numpy >=2.0.0


  run:
    - python
    - {{ pin_compatible('numpy') }}
    - dill
    - gdal >=3.0.4
    - matplotlib-base
    - meshpy
    - netcdf4
    - pandas
    - Pmw
    - pymetis
    - pytest
    - pyproj
    - pytz 
    - scipy
    - utm

test:
  imports:
    - anuga
  commands:
    - pytest --pyargs anuga
  requires:
    - pytest

about:
  home: https://github.com/anuga-community/anuga_core
  summary: A set of python modules for tsunami and flood modelling
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - stoiver
