{% set name = "anuga" %}
{% set version = "3.1.9" %}
{% set sha = "62c45b025272bd33318b33d2fa51a9134e84254d13e8ab3814be697cdcc5074c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anuga-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: True  # [py<3.9]  # (1) Requires Python 3.9 or higher

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - gcc_win-64                 # [win]
    - gxx_win-64                 # [win]
    - libpython                  # [win]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - python 
    - libpython  # [win]
    - pip
    - cython
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - dill
    - future
    - gdal >=3.0.4
    - matplotlib-base
    - meshpy
    - netcdf4
    - Pmw
    - pymetis
    - pytest
    - pytz 
    - scipy
    - utm

test:
  imports:
    - anuga
  commands:
    - pytest --pyargs anuga
  requires:
    - pytest

about:
  home: https://github.com/anuga-community/anuga_core
  summary: A set of python modules for tsunami and flood modelling
  license: Based on Apache License 2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - stoiver
